version: '3.3'

services: 
  mysqldb:
    
    image: mysql
    container_name: mysqldb
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes: 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/mysql
  app:
    build:
      context: .
    image: miraclesheep/minecraft-webserver:latest
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    volumes: 
      - ./app:/app
    depends_on:
      - mysqldb
    command: sh -c "/wait && node server.js"
    environment:
      - WAIT_HOSTS=mysqldb:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=30
    container_name: minecraft-webserver
    stdin_open: true
    tty: true

volumes: 
  db-data: