version: '3.3'

services: 
  mysqldb:
    
    image: mysql
    container_name: mysqldb
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    volumes: 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
  app:
    build:
      context: .
    image: miraclesheep/minecraft-webserver:latest
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    volumes: 
      - ./app:/app
      - /app/node_modules
    depends_on:
      - mysqldb
    container_name: minecraft-webserver
    stdin_open: true
    tty: true

volumes: 
  db-config:
  db-data: